# Generated by Django 5.2.1 on 2025-06-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secciones_inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuadorRiego',
            fields=[
                ('id_actuador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_actuador', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_activacion', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secciones_inv.seccioncultivo')),
            ],
        ),
    ]
