# Generated by Django 5.2.1 on 2025-05-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('used_for', models.CharField(max_length=100)),
                ('application_method', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilograms'), ('L', 'Liters')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('local_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
