# Generated by Django 5.2.1 on 2025-05-18 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Suelo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('area', models.FloatField(help_text='In m2')),
                ('estimated_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('MECANIZED', 'Mechanized')], max_length=20)),
                ('date', models.DateField()),
                ('greenhouse', models.BooleanField(default=False)),
                ('season', models.CharField(default='2025-A', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.product')),
                ('soil_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suelo.soilanalysis')),
            ],
        ),
    ]
