# Generated by Django 5.2.1 on 2025-06-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invernadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionCultivo',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seccion', models.CharField(max_length=100)),
                ('cultivo_actual', models.CharField(max_length=50)),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invernadero.invernadero')),
            ],
        ),
    ]
