# Generated by Django 5.2.1 on 2025-06-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCultivo',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cultivo', models.CharField(max_length=50)),
                ('parametro', models.CharField(max_length=50)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
    ]
