# Generated by Django 5.2.1 on 2025-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sowings', models.PositiveIntegerField(default=0)),
                ('total_soil_analyses', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
