# Generated by Django 5.2.1 on 2025-06-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_spacing', models.FloatField(help_text='In meters')),
                ('quantity_per_area', models.FloatField(help_text='Plant/m2 ratio')),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilograms'), ('L', 'Liters'), ('m2', 'Square meters')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
