# Generated by Django 5.2.1 on 2025-06-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField()),
                ('description', models.CharField()),
                ('location', models.CharField()),
                ('install_date', models.DateTimeField()),
            ],
        ),
    ]
