# Generated by Django 5.2.1 on 2025-06-04 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Siembra', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('solution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Siembra.sowing')),
            ],
        ),
    ]
